In [1]:
person = {
    "first":"Kumar",
    "last":"Das",
    "email":"kumardas@gmail.com",
}
person


{'first': 'Kumar', 'last': 'Das', 'email': 'kumardas@gmail.com'}

In [29]:
people={
    "first" : ["Kumar",'Ajay','Lokesh'],
    "last" : ["Das",'A','M'],
    "email" : ["kumardas@gmail.com",'ajay@email.com','lokesh@email.com']
}
people

{'first': ['Kumar', 'Ajay', 'Lokesh'],
 'last': ['Das', 'A', 'M'],
 'email': ['kumardas@gmail.com', 'ajay@email.com', 'lokesh@email.com']}

In [3]:
import pandas as pd
sr = pd.DataFrame({"Name" : ["Raj","Ajay"]})
sr

Name
0   Raj
1  Ajay

In [4]:
df = pd.DataFrame({"Name":["Raj","Ajay"],
                "Age":[25,30]})
print(df.Name,"\n",df.Age)

0     Raj
1    Ajay
Name: Name, dtype: object 
 0    25
1    30
Name: Age, dtype: int64


In [5]:
df[['Name','Age']]

Name  Age
0   Raj   25
1  Ajay   30

In [6]:
type(sr['Name'])

pandas.core.series.Series

In [7]:
people={
    "first" : ["kumar",'Ajay','Lokesh'],
    "last" : ["Das",'A','M'],
    "email" : ["kumardas@gmail.com",'ajay@email.com','lokesh@email.com']
}
people['email']


['kumardas@gmail.com', 'ajay@email.com', 'lokesh@email.com']

In [8]:
people={
    "first" : ["Kumar",'Ajay','Lokesh'],
    "last" : ["Das",'A','M'],
    "email" : ["kumardas@gmail.com",'ajay@email.com','lokesh@email.com']
}
df=pd.DataFrame(people)


In [27]:
df

first last               email
0   Kumar  Das  kumardas@gmail.com
1    Ajay    A      ajay@email.com
2  Lokesh    M    lokesh@email.com

In [9]:
print(type(df['email']))

<class 'pandas.core.series.Series'>


In [10]:
print(df)

    first last               email
0   Kumar  Das  kumardas@gmail.com
1    Ajay    A      ajay@email.com
2  Lokesh    M    lokesh@email.com


In [11]:
df['email']

0    kumardas@gmail.com
1        ajay@email.com
2      lokesh@email.com
Name: email, dtype: object

In [12]:
df = pd.read_csv('data/survey_results_public.csv')


In [13]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife'

In [14]:
df['MainBranch']

0                   I am a student who is learning to code
1                   I am a student who is learning to code
2        I am not primarily a developer, but I write co...
3                           I am a developer by profession
4                           I am a developer by profession
                               ...                        
88878                                                  NaN
88879                                                  NaN
88880                                                  NaN
88881                                                  NaN
88882                                                  NaN
Name: MainBranch, Length: 88883, dtype: object

In [15]:
df = pd.read_csv('data/survey_results_public.csv')

In [16]:
df

Respondent                                         MainBranch Hobbyist  \
0               1             I am a student who is learning to code      Yes   
1               2             I am a student who is learning to code       No   
2               3  I am not primarily a developer, but I write co...      Yes   
3               4                     I am a developer by profession       No   
4               5                     I am a developer by profession      Yes   
...           ...                                                ...      ...   
88878       88377                                                NaN      Yes   
88879       88601                                                NaN       No   
88880       88802                                                NaN       No   
88881       88816                                                NaN       No   
88882       88863                                                NaN      Yes   

                                             OpenSourcer  \
0                                                  Never   
1                                Less than once per year   
2                                                  Never   
3                                                  Never   
4                             Once a month or more often   
...                                                  ...   
88878  Less than once a month but more than once per ...   
88879                                              Never   
88880                                              Never   
88881                                              Never   
88882                            Less than once per year   

                                              OpenSource  \
0      The quality of OSS and closed source software ...   
1      The quality of OSS and closed source software ...   
2      The quality of OSS and closed source software ...   
3      The quality of OSS and closed source software ...   
4      OSS is, on average, of HIGHER quality than pro...   
...                                                  ...   
88878  The quality of OSS and closed source software ...   
88879  The quality of OSS and closed source software ...   
88880                                                NaN   
88881  OSS is, on average, of HIGHER quality than pro...   
88882  OSS is, on average, of HIGHER quality than pro...   

                                              Employment  \
0                 Not employed, and not looking for work   
1                     Not employed, but looking for work   
2                                     Employed full-time   
3                                     Employed full-time   
4                                     Employed full-time   
...                                                  ...   
88878             Not employed, and not looking for work   
88879                                                NaN   
88880                                 Employed full-time   
88881  Independent contractor, freelancer, or self-em...   
88882             Not employed, and not looking for work   

                      Country         Student  \
0              United Kingdom              No   
1      Bosnia and Herzegovina  Yes, full-time   
2                    Thailand              No   
3               United States              No   
4                     Ukraine              No   
...                       ...             ...   
88878                  Canada              No   
88879                     NaN             NaN   
88880                     NaN             NaN   
88881                     NaN             NaN   
88882                   Spain  Yes, full-time   

                                                 EdLevel  \
0                              Primary/elementary school   
1      Secondary school (e.g. American high school, G...   
2               Bachelor’s degree (BA, BS, B.Eng., etc.)   
3               Bachelor’s degree (BA, BS,

In [17]:
df.shape


(88883, 85)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Respondent              88883 non-null  int64  
 1   MainBranch              88331 non-null  object 
 2   Hobbyist                88883 non-null  object 
 3   OpenSourcer             88883 non-null  object 
 4   OpenSource              86842 non-null  object 
 5   Employment              87181 non-null  object 
 6   Country                 88751 non-null  object 
 7   Student                 87014 non-null  object 
 8   EdLevel                 86390 non-null  object 
 9   UndergradMajor          75614 non-null  object 
 10  EduOther                84260 non-null  object 
 11  OrgSize                 71791 non-null  object 
 12  DevType                 81335 non-null  object 
 13  YearsCode               87938 non-null  object 
 14  Age1stCode              87634 non-null

In [42]:
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   

                  OpenSourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   

                               Employment                 Country  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   
2                      Employed full-time                Thailand   
3                      Employed full-time           United States   
4                      Employed full-time                 Ukraine   

          Student                                            EdLevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  ...  \
0                                                NaN  ...   
1                                                NaN  ...   
2                      Web development or web design  ...   
3  Computer science, computer engineering, or sof...  ...   
4  Computer science, computer engineering, or sof...  ...   

                             WelcomeChange  \
0  Just as welcome now as I felt last year   
1  Just as welcome now as I felt last year   
2  Just as welcome now as I felt last year   
3  Just as welcome now as I felt last year   
4  Just as welcome now as I felt last year   

                                        SONewContent   Age Gender Trans  \
0  Tech articles written by other developers;Indu...  14.0    Man    No   
1  Tech articles written by other developers;Indu...  19.0    Man    No   
2  Tech meetups or events in your area;Courses on...  28.0    Man    No   
3  Tech articles written by other developers;Indu...  22.0    Man    No   
4  Tech meetups or events in your area;Courses on...  30.0    Man    No   

                 Sexuality                                 Ethnicity  \
0  Straight / Heterosexual                                       NaN   
1  Straight / Heterosexual                                       NaN   
2  Straight / Heterosexual                                       NaN   
3  Straight / Heterosexual              White or of European descent   
4  Straight / Heterosexual  White or of European descent;Multiracial   

  Dependents           SurveyLength                  SurveyEase  
0         No  Appropriate in length  Neither easy nor difficult  
1         No  Appropriate in length  Neither easy nor difficult  
2        Yes  Appropriate in length  Neither easy nor difficult  
3         No  Appropriate in length                        Easy  
4         No  Appropriate in length                        Easy  

[5 rows x 85 columns]

In [43]:
df.tail()

Respondent MainBranch Hobbyist  \
88878       88377        NaN      Yes   
88879       88601        NaN       No   
88880       88802        NaN       No   
88881       88816        NaN       No   
88882       88863        NaN      Yes   

                                             OpenSourcer  \
88878  Less than once a month but more than once per ...   
88879                                              Never   
88880                                              Never   
88881                                              Never   
88882                            Less than once per year   

                                              OpenSource  \
88878  The quality of OSS and closed source software ...   
88879  The quality of OSS and closed source software ...   
88880                                                NaN   
88881  OSS is, on average, of HIGHER quality than pro...   
88882  OSS is, on average, of HIGHER quality than pro...   

                                              Employment Country  \
88878             Not employed, and not looking for work  Canada   
88879                                                NaN     NaN   
88880                                 Employed full-time     NaN   
88881  Independent contractor, freelancer, or self-em...     NaN   
88882             Not employed, and not looking for work   Spain   

              Student                             EdLevel  \
88878              No           Primary/elementary school   
88879             NaN                                 NaN   
88880             NaN                                 NaN   
88881             NaN                                 NaN   
88882  Yes, full-time  Professional degree (JD, MD, etc.)   

                                          UndergradMajor  ...  \
88878                                                NaN  ...   
88879                                                NaN  ...   
88880                                                NaN  ...   
88881                                                NaN  ...   
88882  Computer science, computer engineering, or sof...  ...   

                                  WelcomeChange  \
88878                                       NaN   
88879                                       NaN   
88880                                       NaN   
88881                                       NaN   
88882  Somewhat less welcome now than last year   

                                            SONewContent   Age Gender Trans  \
88878  Tech articles written by other developers;Tech...   NaN    Man    No   
88879                                                NaN   NaN    NaN   NaN   
88880                                                NaN   NaN    NaN   NaN   
88881                                                NaN   NaN    NaN   NaN   
88882  Tech articles written by other developers;Indu...  18.0    Man    No   

                     Sexuality  \
88878                      NaN   
88879                      NaN   
88880                      NaN   
88881                      NaN   
88882  Straight / Heterosexual   

                                               Ethnicity Dependents  \
88878                                                NaN         No   
88879                                                NaN        NaN   
88880                                                NaN        NaN   
88881                                                NaN        NaN   
88882  Hispanic or Latino/Latina;White or of European...         No   

                SurveyLength SurveyEase  
88878  Appropriate in length       Easy  
88879                    NaN        NaN  
88880                    NaN        NaN  
88881                    NaN        NaN  
88882  Appropriate in length       Easy  

[5 rows x 85 columns]

In [20]:
pd.set_option('display.max_rows',87)
print(df)

       Respondent                                         MainBranch Hobbyist  \
0               1             I am a student who is learning to code      Yes   
1               2             I am a student who is learning to code       No   
2               3  I am not primarily a developer, but I write co...      Yes   
3               4                     I am a developer by profession       No   
4               5                     I am a developer by profession      Yes   
...           ...                                                ...      ...   
88878       88377                                                NaN      Yes   
88879       88601                                                NaN       No   
88880       88802                                                NaN       No   
88881       88816                                                NaN       No   
88882       88863                                                NaN      Yes   

                           

In [3]:
import pandas as pd
pd.set_option('display.max_columns',10)
df = pd.read_csv('data/survey_results_public.csv')
print(df)

       Respondent                                         MainBranch Hobbyist  \
0               1             I am a student who is learning to code      Yes   
1               2             I am a student who is learning to code       No   
2               3  I am not primarily a developer, but I write co...      Yes   
3               4                     I am a developer by profession       No   
4               5                     I am a developer by profession      Yes   
...           ...                                                ...      ...   
88878       88377                                                NaN      Yes   
88879       88601                                                NaN       No   
88880       88802                                                NaN       No   
88881       88816                                                NaN       No   
88882       88863                                                NaN      Yes   

                           

In [22]:
!pip install scipy
  # For mode calculation


   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.6 MB ? eta -:--:--
    --------------------------------------- 0.8/38.6 MB 2.4 MB/s eta 0:00:16
   - -------------------------------------- 1.6/38.6 MB 2.7 MB/s eta 0:00:14
   -- ------------------------------------- 2.1/38.6 MB 2.7 MB/s eta 0:00:14
   -- ------------------------------------- 2.9/38.6 MB 2.8 MB/s eta 0:00:13
   --- ------------------------------------ 3.4/38.6 MB 2.8 MB/s eta 0:00:13
   ---- ----------------------------------- 3.9/38.6 MB 2.9 MB/s eta 0:00:13
   ----- ---------------------------------- 5.2/38.6 MB 3.2 MB/s eta 0:00:11
   ------ --------------------------------- 6.6/38.6 MB 3.5 MB/s eta 0:00:10
   -------- ------------------------------- 7.9/38.6 MB 3.8 MB/s eta 0:00:09
   --------- ------------------------------ 9.2/38.6 MB 4.1 MB/s eta 0:00:08
   ----------- ---------------------------- 10.7/38.6 MB 4.3 MB/s eta 0:00:07
   ---------

In [23]:
import numpy as np
from scipy import stats 

In [24]:
array_3d = np.random.randint(1, 100, (3, 4, 5))  # Random integers from 1 to 99
print("3D Array:\n", array_3d)

3D Array:
 [[[57 89 16 96 62]
  [72 42 85 88 20]
  [16 58 59 34 47]
  [28 21 45 15 70]]

 [[58 16 28 27 42]
  [96 37  3 77 82]
  [40 35 96 68 97]
  [41 79 31 33 12]]

 [[45  5 42 45 69]
  [68 72 20 87 36]
  [95 39 48 67 94]
  [79 16 83 93 54]]]


In [25]:
#Calculating Max
max_value = np.max(array_3d)
print("Maximum value:", max_value)


Maximum value: 97


In [26]:
#Calculating Min
min_value = np.min(array_3d)
print("Minimum value:", min_value)


Minimum value: 3


In [27]:
#Mean 
mean_value = np.mean(array_3d)
print("Mean value:", mean_value)


Mean value: 52.916666666666664


In [29]:
#Mode
mode_value = stats.mode(array_3d, axis=None)
print("Mode value:", mode_value.mode.item(), " | Count:", mode_value.count.item())



Mode value: 16  | Count: 4


In [30]:
#Median
median_value = np.median(array_3d)
print("Median value:", median_value)


Median value: 47.5


In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('data/survey_results_public.csv')

In [9]:
df.loc[2,'Age'] #get value of age in 2nd row

np.float64(28.0)

In [13]:
df.loc[0,'Age']

np.float64(14.0)

In [11]:
df.loc[df['Age']>30]

Respondent                                         MainBranch Hobbyist  \
6               7                     I am a developer by profession       No   
13             14                     I am a developer by profession      Yes   
18             19                     I am a developer by profession      Yes   
19             20  I am not primarily a developer, but I write co...       No   
21             22                     I am a developer by profession      Yes   
...           ...                                                ...      ...   
88859       85642                                                NaN       No   
88863       85961                                                NaN      Yes   
88865       86566                                                NaN      Yes   
88870       87352                                                NaN      Yes   
88876       88212                                                NaN       No   

                                             OpenSourcer  \
6                                                  Never   
13                               Less than once per year   
18                                                 Never   
19                                                 Never   
21                               Less than once per year   
...                                                  ...   
88859                            Less than once per year   
88863                            Less than once per year   
88865  Less than once a month but more than once per ...   
88870                            Less than once per year   
88876                            Less than once per year   

                                              OpenSource  ...  \
6      The quality of OSS and closed source software ...  ...   
13     The quality of OSS and closed source software ...  ...   
18     The quality of OSS and closed source software ...  ...   
19     OSS is, on average, of HIGHER quality than pro...  ...   
21     OSS is, on average, of HIGHER quality than pro...  ...   
...                                                  ...  ...   
88859  OSS is, on average, of LOWER quality than prop...  ...   
88863  The quality of OSS and closed source software ...  ...   
88865  OSS is, on average, of HIGHER quality than pro...  ...   
88870                                                NaN  ...   
88876  OSS is, on average, of HIGHER quality than pro...  ...   

                     Sexuality                     Ethnicity Dependents  \
6      Straight / Heterosexual  White or of European descent        Yes   
13     Straight / Heterosexual  White or of European descent         No   
18     Straight / Heterosexual     Hispanic or Latino/Latina        Yes   
19     Straight / Heterosexual  White or of European descent        Yes   
21     Straight / Heterosexual  White or of European descent        Yes   
...                        ...                           ...        ...   
88859  Bisexual;Gay or Lesbian  White or of European descent         No   
88863           Gay or Lesbian  White or of European descent         No   
88865                      NaN  White or of European descent         No   
88870                      NaN                           NaN         No   
88876  Straight / Heterosexual  White or of European descent         No   

                SurveyLength                  SurveyEase  
6      Appropriate in length  Neither easy nor difficult  
13                 Too short                        Easy  
18                  Too long                        Easy  
19     Appropriate in length                        Easy  
21     Appropriate in length                        Easy  
...                      ...                         ...  
88859  Appropriate in length                        Easy  
88863  Appropriate in length                   Difficult  
88865  Appropriate in length                        Easy  
88870                    NaN             

In [14]:
df.iloc[3,2]

'No'

In [17]:
df.iloc[0:11]

Respondent                                         MainBranch Hobbyist  \
0            1             I am a student who is learning to code      Yes   
1            2             I am a student who is learning to code       No   
2            3  I am not primarily a developer, but I write co...      Yes   
3            4                     I am a developer by profession       No   
4            5                     I am a developer by profession      Yes   
5            6  I am not primarily a developer, but I write co...      Yes   
6            7                     I am a developer by profession       No   
7            8                        I code primarily as a hobby      Yes   
8            9                     I am a developer by profession      Yes   
9           10                     I am a developer by profession      Yes   
10          11                        I code primarily as a hobby      Yes   

                   OpenSourcer  \
0                        Never   
1      Less than once per year   
2                        Never   
3                        Never   
4   Once a month or more often   
5                        Never   
6                        Never   
7      Less than once per year   
8   Once a month or more often   
9   Once a month or more often   
10  Once a month or more often   

                                           OpenSource  ...  \
0   The quality of OSS and closed source software ...  ...   
1   The quality of OSS and closed source software ...  ...   
2   The quality of OSS and closed source software ...  ...   
3   The quality of OSS and closed source software ...  ...   
4   OSS is, on average, of HIGHER quality than pro...  ...   
5   The quality of OSS and closed source software ...  ...   
6   The quality of OSS and closed source software ...  ...   
7   OSS is, on average, of HIGHER quality than pro...  ...   
8   The quality of OSS and closed source software ...  ...   
9   OSS is, on average, of HIGHER quality than pro...  ...   
10  The quality of OSS and closed source software ...  ...   

                                          Sexuality  \
0                           Straight / Heterosexual   
1                           Straight / Heterosexual   
2                           Straight / Heterosexual   
3                           Straight / Heterosexual   
4                           Straight / Heterosexual   
5                           Straight / Heterosexual   
6                           Straight / Heterosexual   
7                           Straight / Heterosexual   
8                                          Bisexual   
9                                               NaN   
10  Bisexual;Gay or Lesbian;Straight / Heterosexual   

                                            Ethnicity Dependents  \
0                                                 NaN         No   
1                                                 NaN         No   
2                                                 NaN        Yes   
3                        White or of European descent         No   
4            White or of European descent;Multiracial         No   
5                                          East Asian         No   
6                        White or of European descent        Yes   
7                                                 NaN        NaN   
8                        White or of European descent         No   
9                                                 NaN        Yes   
10  Black or of African descent;East Asian;Hispani...         No   

             SurveyLength                  SurveyEase  
0   Appropriate in length  Neither easy nor difficult  
1   Appropriate in length  Neither easy nor difficult  
2   Appropriate in length  Neither easy nor difficult  
3   Appropriate in length                        Easy  
4   Appropriate in length                        Easy  
5                Too long  Neither easy nor difficult  
6   Appropriate in length  Neither easy nor

In [19]:
df.head(10)

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   
5           6  I am not primarily a developer, but I write co...      Yes   
6           7                     I am a developer by profession       No   
7           8                        I code primarily as a hobby      Yes   
8           9                     I am a developer by profession      Yes   
9          10                     I am a developer by profession      Yes   

                  OpenSourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   
5                       Never   
6                       Never   
7     Less than once per year   
8  Once a month or more often   
9  Once a month or more often   

                                          OpenSource  ...  \
0  The quality of OSS and closed source software ...  ...   
1  The quality of OSS and closed source software ...  ...   
2  The quality of OSS and closed source software ...  ...   
3  The quality of OSS and closed source software ...  ...   
4  OSS is, on average, of HIGHER quality than pro...  ...   
5  The quality of OSS and closed source software ...  ...   
6  The quality of OSS and closed source software ...  ...   
7  OSS is, on average, of HIGHER quality than pro...  ...   
8  The quality of OSS and closed source software ...  ...   
9  OSS is, on average, of HIGHER quality than pro...  ...   

                 Sexuality                                 Ethnicity  \
0  Straight / Heterosexual                                       NaN   
1  Straight / Heterosexual                                       NaN   
2  Straight / Heterosexual                                       NaN   
3  Straight / Heterosexual              White or of European descent   
4  Straight / Heterosexual  White or of European descent;Multiracial   
5  Straight / Heterosexual                                East Asian   
6  Straight / Heterosexual              White or of European descent   
7  Straight / Heterosexual                                       NaN   
8                 Bisexual              White or of European descent   
9                      NaN                                       NaN   

  Dependents           SurveyLength                  SurveyEase  
0         No  Appropriate in length  Neither easy nor difficult  
1         No  Appropriate in length  Neither easy nor difficult  
2        Yes  Appropriate in length  Neither easy nor difficult  
3         No  Appropriate in length                        Easy  
4         No  Appropriate in length                        Easy  
5         No               Too long  Neither easy nor difficult  
6        Yes  Appropriate in length  Neither easy nor difficult  
7        NaN  Appropriate in length  Neither easy nor difficult  
8         No  Appropriate in length  Neither easy nor difficult  
9        Yes               Too long                   Difficult  

[10 rows x 85 columns]

In [20]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife'

In [21]:
df['MainBranch']

0                   I am a student who is learning to code
1                   I am a student who is learning to code
2        I am not primarily a developer, but I write co...
3                           I am a developer by profession
4                           I am a developer by profession
                               ...                        
88878                                                  NaN
88879                                                  NaN
88880                                                  NaN
88881                                                  NaN
88882                                                  NaN
Name: MainBranch, Length: 88883, dtype: object

In [23]:
df[['MainBranch','Age']]

MainBranch   Age
0                 I am a student who is learning to code  14.0
1                 I am a student who is learning to code  19.0
2      I am not primarily a developer, but I write co...  28.0
3                         I am a developer by profession  22.0
4                         I am a developer by profession  30.0
...                                                  ...   ...
88878                                                NaN   NaN
88879                                                NaN   NaN
88880                                                NaN   NaN
88881                                                NaN   NaN
88882                                                NaN  18.0

[88883 rows x 2 columns]

In [24]:
df['Age'].value_counts()

Age
25.0    4669
24.0    4428
27.0    4418
26.0    4397
28.0    4387
        ... 
37.3       1
33.5       1
53.8       1
31.4       1
87.0       1
Name: count, Length: 126, dtype: int64

In [25]:
df.loc[[0]]

Respondent                              MainBranch Hobbyist OpenSourcer  \
0           1  I am a student who is learning to code      Yes       Never   

                                          OpenSource  ...  \
0  The quality of OSS and closed source software ...  ...   

                 Sexuality Ethnicity Dependents           SurveyLength  \
0  Straight / Heterosexual       NaN         No  Appropriate in length   

                   SurveyEase  
0  Neither easy nor difficult  

[1 rows x 85 columns]

In [26]:
df.loc[[0,2]]

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
2           3  I am not primarily a developer, but I write co...      Yes   

  OpenSourcer                                         OpenSource  ...  \
0       Never  The quality of OSS and closed source software ...  ...   
2       Never  The quality of OSS and closed source software ...  ...   

                 Sexuality Ethnicity Dependents           SurveyLength  \
0  Straight / Heterosexual       NaN         No  Appropriate in length   
2  Straight / Heterosexual       NaN        Yes  Appropriate in length   

                   SurveyEase  
0  Neither easy nor difficult  
2  Neither easy nor difficult  

[2 rows x 85 columns]

In [32]:
people={
    "first" : ["Kumar",'Ajay','Lokesh'],
    "last" : ["Das",'A','M'],
    "email" : ["kumardas@gmail.com",'ajay@email.com','lokesh@email.com']
}
people


{'first': ['Kumar', 'Ajay', 'Lokesh'],
 'last': ['Das', 'A', 'M'],
 'email': ['kumardas@gmail.com', 'ajay@email.com', 'lokesh@email.com']}

In [33]:
pdf = pd.DataFrame(people)

In [35]:
pdf.loc[[0,1],['email','last']]

email last
0  kumardas@gmail.com  Das
1      ajay@email.com    A

In [37]:
pdf.loc[[0,2]]

first last               email
0   Kumar  Das  kumardas@gmail.com
2  Lokesh    M    lokesh@email.com

In [40]:
pdf.loc[[0,1],'last']

0    Das
1      A
Name: last, dtype: object

In [42]:
pdf.iloc[[0,2,1]]

first last               email
0   Kumar  Das  kumardas@gmail.com
2  Lokesh    M    lokesh@email.com
1    Ajay    A      ajay@email.com

In [44]:
df.loc[1:3,'MainBranch':'Employment']

MainBranch Hobbyist  \
1             I am a student who is learning to code       No   
2  I am not primarily a developer, but I write co...      Yes   
3                     I am a developer by profession       No   

               OpenSourcer                                         OpenSource  \
1  Less than once per year  The quality of OSS and closed source software ...   
2                    Never  The quality of OSS and closed source software ...   
3                    Never  The quality of OSS and closed source software ...   

                           Employment  
1  Not employed, but looking for work  
2                  Employed full-time  
3                  Employed full-time

In [45]:
df.index

RangeIndex(start=0, stop=88883, step=1)

In [46]:
pdf.index

RangeIndex(start=0, stop=3, step=1)

In [58]:
people={
    "first" : ["Kumar",'Ajay','Lokesh'],
    "last" : ["Das",'A','M'],
    "email" : ["kumardas@gmail.com",'ajay@email.com','lokesh@email.com'],
    "Phone_Number" : ["9834986656",'7896745678','8877665544']
}
people
pdf = pd.DataFrame(people)
 

In [52]:
   pdf.set_index('Phone_Number')

first last               email
Phone_Number                                 
9834986656     Kumar  Das  kumardas@gmail.com
7896745678      Ajay    A      ajay@email.com
8877665544    Lokesh    M    lokesh@email.com

In [53]:
pdf

first last               email Phone_Number
0   Kumar  Das  kumardas@gmail.com   9834986656
1    Ajay    A      ajay@email.com   7896745678
2  Lokesh    M    lokesh@email.com   8877665544

In [59]:
pdf.set_index('Phone_Number', inplace = True)
pdf.index

Index(['9834986656', '7896745678', '8877665544'], dtype='object', name='Phone_Number')

In [63]:
pdf.loc['7896745678']

first              Ajay
last                  A
email    ajay@email.com
Name: 7896745678, dtype: object

In [61]:
pdf.iloc[1]

first              Ajay
last                  A
email    ajay@email.com
Name: 7896745678, dtype: object

In [64]:
pdf.reset_index(inplace = True)

In [65]:
pdf

Phone_Number   first last               email
0   9834986656   Kumar  Das  kumardas@gmail.com
1   7896745678    Ajay    A      ajay@email.com
2   8877665544  Lokesh    M    lokesh@email.com

In [66]:
pdf.sort_index()

Phone_Number   first last               email
0   9834986656   Kumar  Das  kumardas@gmail.com
1   7896745678    Ajay    A      ajay@email.com
2   8877665544  Lokesh    M    lokesh@email.com

In [67]:
df


Respondent                                         MainBranch Hobbyist  \
0               1             I am a student who is learning to code      Yes   
1               2             I am a student who is learning to code       No   
2               3  I am not primarily a developer, but I write co...      Yes   
3               4                     I am a developer by profession       No   
4               5                     I am a developer by profession      Yes   
...           ...                                                ...      ...   
88878       88377                                                NaN      Yes   
88879       88601                                                NaN       No   
88880       88802                                                NaN       No   
88881       88816                                                NaN       No   
88882       88863                                                NaN      Yes   

                                             OpenSourcer  \
0                                                  Never   
1                                Less than once per year   
2                                                  Never   
3                                                  Never   
4                             Once a month or more often   
...                                                  ...   
88878  Less than once a month but more than once per ...   
88879                                              Never   
88880                                              Never   
88881                                              Never   
88882                            Less than once per year   

                                              OpenSource  ...  \
0      The quality of OSS and closed source software ...  ...   
1      The quality of OSS and closed source software ...  ...   
2      The quality of OSS and closed source software ...  ...   
3      The quality of OSS and closed source software ...  ...   
4      OSS is, on average, of HIGHER quality than pro...  ...   
...                                                  ...  ...   
88878  The quality of OSS and closed source software ...  ...   
88879  The quality of OSS and closed source software ...  ...   
88880                                                NaN  ...   
88881  OSS is, on average, of HIGHER quality than pro...  ...   
88882  OSS is, on average, of HIGHER quality than pro...  ...   

                     Sexuality  \
0      Straight / Heterosexual   
1      Straight / Heterosexual   
2      Straight / Heterosexual   
3      Straight / Heterosexual   
4      Straight / Heterosexual   
...                        ...   
88878                      NaN   
88879                      NaN   
88880                      NaN   
88881                      NaN   
88882  Straight / Heterosexual   

                                               Ethnicity Dependents  \
0                                                    NaN         No   
1                                                    NaN         No   
2                                                    NaN        Yes   
3                           White or of European descent         No   
4               White or of European descent;Multiracial         No   
...                                                  ...        ...   
88878                                                NaN         No   
88879                                                NaN        NaN   
88880                                                NaN        NaN   
88881                                                NaN        NaN   
88882  Hispanic or Latino/Latina;White or of European...         No   

                SurveyLength                  SurveyEase  
0      Appropriate in length  Neither easy nor difficult  
1      Appropriate in length  Neither easy nor difficult  
2      Appropriate in length  Neither easy nor difficult  
3      Appropriate in length      

In [68]:
df.set_index('Respondent', inplace = True)

In [69]:
df

MainBranch Hobbyist  \
Respondent                                                               
1                      I am a student who is learning to code      Yes   
2                      I am a student who is learning to code       No   
3           I am not primarily a developer, but I write co...      Yes   
4                              I am a developer by profession       No   
5                              I am a developer by profession      Yes   
...                                                       ...      ...   
88377                                                     NaN      Yes   
88601                                                     NaN       No   
88802                                                     NaN       No   
88816                                                     NaN       No   
88863                                                     NaN      Yes   

                                                  OpenSourcer  \
Respondent                                                      
1                                                       Never   
2                                     Less than once per year   
3                                                       Never   
4                                                       Never   
5                                  Once a month or more often   
...                                                       ...   
88377       Less than once a month but more than once per ...   
88601                                                   Never   
88802                                                   Never   
88816                                                   Never   
88863                                 Less than once per year   

                                                   OpenSource  \
Respondent                                                      
1           The quality of OSS and closed source software ...   
2           The quality of OSS and closed source software ...   
3           The quality of OSS and closed source software ...   
4           The quality of OSS and closed source software ...   
5           OSS is, on average, of HIGHER quality than pro...   
...                                                       ...   
88377       The quality of OSS and closed source software ...   
88601       The quality of OSS and closed source software ...   
88802                                                     NaN   
88816       OSS is, on average, of HIGHER quality than pro...   
88863       OSS is, on average, of HIGHER quality than pro...   

                                                   Employment  ...  \
Respondent                                                     ...   
1                      Not employed, and not looking for work  ...   
2                          Not employed, but looking for work  ...   
3                                          Employed full-time  ...   
4                                          Employed full-time  ...   
5                                          Employed full-time  ...   
...                                                       ...  ...   
88377                  Not employed, and not looking for work  ...   
88601                                                     NaN  ...   
88802                                      Employed full-time  ...   
88816       Independent contractor, freelancer, or self-em...  ...   
88863                  Not employed, and not looking for work  ...   

                          Sexuality  \
Respondent                            
1           Straight / Heterosexual   
2           Straight / Heterosexual   
3           Straight / Heterosexual   
4           Straight / Heterosexual   
5           Straight / Heterosexual   
...                             ...   
88377                           NaN   
88601                           NaN   
88802                           NaN   
88816                           NaN   
88863       Strai

In [70]:
df.sort_index(ascending = False)

MainBranch Hobbyist  \
Respondent                                                               
88883                          I am a developer by profession      Yes   
88882                          I am a developer by profession      Yes   
88881                          I am a developer by profession      Yes   
88880       I am not primarily a developer, but I write co...      Yes   
88879                          I am a developer by profession      Yes   
...                                                       ...      ...   
5                              I am a developer by profession      Yes   
4                              I am a developer by profession       No   
3           I am not primarily a developer, but I write co...      Yes   
2                      I am a student who is learning to code       No   
1                      I am a student who is learning to code      Yes   

                           OpenSourcer  \
Respondent                               
88883       Once a month or more often   
88882                            Never   
88881       Once a month or more often   
88880                            Never   
88879                            Never   
...                                ...   
5           Once a month or more often   
4                                Never   
3                                Never   
2              Less than once per year   
1                                Never   

                                                   OpenSource  \
Respondent                                                      
88883       OSS is, on average, of HIGHER quality than pro...   
88882       OSS is, on average, of LOWER quality than prop...   
88881       OSS is, on average, of HIGHER quality than pro...   
88880       The quality of OSS and closed source software ...   
88879       The quality of OSS and closed source software ...   
...                                                       ...   
5           OSS is, on average, of HIGHER quality than pro...   
4           The quality of OSS and closed source software ...   
3           The quality of OSS and closed source software ...   
2           The quality of OSS and closed source software ...   
1           The quality of OSS and closed source software ...   

                                        Employment  ...  \
Respondent                                          ...   
88883                           Employed full-time  ...   
88882                           Employed full-time  ...   
88881                           Employed full-time  ...   
88880                           Employed full-time  ...   
88879                           Employed full-time  ...   
...                                            ...  ...   
5                               Employed full-time  ...   
4                               Employed full-time  ...   
3                               Employed full-time  ...   
2               Not employed, but looking for work  ...   
1           Not employed, and not looking for work  ...   

                          Sexuality                                 Ethnicity  \
Respondent                                                                      
88883       Straight / Heterosexual              White or of European descent   
88882       Straight / Heterosexual              White or of European descent   
88881       Straight / Heterosexual              White or of European descent   
88880                           NaN                                       NaN   
88879       Straight / Heterosexual              White or of European descent   
...                             ...                                       ...   
5           Straight / Heterosexual  White or of European descent;Multiracial   
4           Straight / Heterosexual              White or of European descent   
3           Straight / Heterosexual                                       NaN   
2           Straight / Heterosexual 

In [77]:
df.reset_index(inplace = True)

In [78]:
df

level_0  index  Respondent  \
0            0      0           1   
1            1      1           2   
2            2      2           3   
3            3      3           4   
4            4      4           5   
...        ...    ...         ...   
88878    88878  88878       88377   
88879    88879  88879       88601   
88880    88880  88880       88802   
88881    88881  88881       88816   
88882    88882  88882       88863   

                                              MainBranch Hobbyist  ...  \
0                 I am a student who is learning to code      Yes  ...   
1                 I am a student who is learning to code       No  ...   
2      I am not primarily a developer, but I write co...      Yes  ...   
3                         I am a developer by profession       No  ...   
4                         I am a developer by profession      Yes  ...   
...                                                  ...      ...  ...   
88878                                                NaN      Yes  ...   
88879                                                NaN       No  ...   
88880                                                NaN       No  ...   
88881                                                NaN       No  ...   
88882                                                NaN      Yes  ...   

                     Sexuality  \
0      Straight / Heterosexual   
1      Straight / Heterosexual   
2      Straight / Heterosexual   
3      Straight / Heterosexual   
4      Straight / Heterosexual   
...                        ...   
88878                      NaN   
88879                      NaN   
88880                      NaN   
88881                      NaN   
88882  Straight / Heterosexual   

                                               Ethnicity Dependents  \
0                                                    NaN         No   
1                                                    NaN         No   
2                                                    NaN        Yes   
3                           White or of European descent         No   
4               White or of European descent;Multiracial         No   
...                                                  ...        ...   
88878                                                NaN         No   
88879                                                NaN        NaN   
88880                                                NaN        NaN   
88881                                                NaN        NaN   
88882  Hispanic or Latino/Latina;White or of European...         No   

                SurveyLength                  SurveyEase  
0      Appropriate in length  Neither easy nor difficult  
1      Appropriate in length  Neither easy nor difficult  
2      Appropriate in length  Neither easy nor difficult  
3      Appropriate in length                        Easy  
4      Appropriate in length                        Easy  
...                      ...                         ...  
88878  Appropriate in length                        Easy  
88879                    NaN                         NaN  
88880                    NaN                         NaN  
88881                    NaN                         NaN  
88882  Appropriate in length                        Easy  

[88883 rows x 87 columns]