In [1]:
person = {
    "first":"Kumar",
    "last":"Das",
    "email":"kumardas@gmail.com",
}
person


{'first': 'Kumar', 'last': 'Das', 'email': 'kumardas@gmail.com'}

In [2]:
people={
    "first" : ["Kumar",'Ajay','Lokesh'],
    "last" : ["Das",'A','M'],
    "email" : ["kumardas@gmail.com",'ajay@email.com','lokesh@email.com']
}
people

{'first': ['Kumar', 'Ajay', 'Lokesh'],
 'last': ['Das', 'A', 'M'],
 'email': ['kumardas@gmail.com', 'ajay@email.com', 'lokesh@email.com']}

In [3]:
import pandas as pd
sr = pd.DataFrame({"Name" : ["Raj","Ajay"]})
sr

Name
0   Raj
1  Ajay

In [4]:
df = pd.DataFrame({"Name":["Raj","Ajay"],
                "Age":[25,30]})
print(df.Name,"\n",df.Age)

0     Raj
1    Ajay
Name: Name, dtype: object 
 0    25
1    30
Name: Age, dtype: int64


In [5]:
df[['Name','Age']]

Name  Age
0   Raj   25
1  Ajay   30

In [6]:
type(sr['Name'])

pandas.core.series.Series

In [7]:
people={
    "first" : ["kumar",'Ajay','Lokesh'],
    "last" : ["Das",'A','M'],
    "email" : ["kumardas@gmail.com",'ajay@email.com','lokesh@email.com']
}
people['email']


['kumardas@gmail.com', 'ajay@email.com', 'lokesh@email.com']

In [8]:
people={
    "first" : ["Kumar",'Ajay','Lokesh'],
    "last" : ["Das",'A','M'],
    "email" : ["kumardas@gmail.com",'ajay@email.com','lokesh@email.com']
}
df=pd.DataFrame(people)


In [27]:
df

first last               email
0   Kumar  Das  kumardas@gmail.com
1    Ajay    A      ajay@email.com
2  Lokesh    M    lokesh@email.com

In [9]:
print(type(df['email']))

<class 'pandas.core.series.Series'>


In [10]:
print(df)

    first last               email
0   Kumar  Das  kumardas@gmail.com
1    Ajay    A      ajay@email.com
2  Lokesh    M    lokesh@email.com


In [11]:
df['email']

0    kumardas@gmail.com
1        ajay@email.com
2      lokesh@email.com
Name: email, dtype: object

In [12]:
df = pd.read_csv('data/survey_results_public.csv')


In [13]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife'

In [14]:
df['MainBranch']

0                   I am a student who is learning to code
1                   I am a student who is learning to code
2        I am not primarily a developer, but I write co...
3                           I am a developer by profession
4                           I am a developer by profession
                               ...                        
88878                                                  NaN
88879                                                  NaN
88880                                                  NaN
88881                                                  NaN
88882                                                  NaN
Name: MainBranch, Length: 88883, dtype: object

In [15]:
df = pd.read_csv('data/survey_results_public.csv')

In [16]:
df

Respondent                                         MainBranch Hobbyist  \
0               1             I am a student who is learning to code      Yes   
1               2             I am a student who is learning to code       No   
2               3  I am not primarily a developer, but I write co...      Yes   
3               4                     I am a developer by profession       No   
4               5                     I am a developer by profession      Yes   
...           ...                                                ...      ...   
88878       88377                                                NaN      Yes   
88879       88601                                                NaN       No   
88880       88802                                                NaN       No   
88881       88816                                                NaN       No   
88882       88863                                                NaN      Yes   

                                             OpenSourcer  \
0                                                  Never   
1                                Less than once per year   
2                                                  Never   
3                                                  Never   
4                             Once a month or more often   
...                                                  ...   
88878  Less than once a month but more than once per ...   
88879                                              Never   
88880                                              Never   
88881                                              Never   
88882                            Less than once per year   

                                              OpenSource  \
0      The quality of OSS and closed source software ...   
1      The quality of OSS and closed source software ...   
2      The quality of OSS and closed source software ...   
3      The quality of OSS and closed source software ...   
4      OSS is, on average, of HIGHER quality than pro...   
...                                                  ...   
88878  The quality of OSS and closed source software ...   
88879  The quality of OSS and closed source software ...   
88880                                                NaN   
88881  OSS is, on average, of HIGHER quality than pro...   
88882  OSS is, on average, of HIGHER quality than pro...   

                                              Employment  \
0                 Not employed, and not looking for work   
1                     Not employed, but looking for work   
2                                     Employed full-time   
3                                     Employed full-time   
4                                     Employed full-time   
...                                                  ...   
88878             Not employed, and not looking for work   
88879                                                NaN   
88880                                 Employed full-time   
88881  Independent contractor, freelancer, or self-em...   
88882             Not employed, and not looking for work   

                      Country         Student  \
0              United Kingdom              No   
1      Bosnia and Herzegovina  Yes, full-time   
2                    Thailand              No   
3               United States              No   
4                     Ukraine              No   
...                       ...             ...   
88878                  Canada              No   
88879                     NaN             NaN   
88880                     NaN             NaN   
88881                     NaN             NaN   
88882                   Spain  Yes, full-time   

                                                 EdLevel  \
0                              Primary/elementary school   
1      Secondary school (e.g. American high school, G...   
2               Bachelor’s degree (BA, BS, B.Eng., etc.)   
3               Bachelor’s degree (BA, BS,

In [17]:
df.shape


(88883, 85)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Respondent              88883 non-null  int64  
 1   MainBranch              88331 non-null  object 
 2   Hobbyist                88883 non-null  object 
 3   OpenSourcer             88883 non-null  object 
 4   OpenSource              86842 non-null  object 
 5   Employment              87181 non-null  object 
 6   Country                 88751 non-null  object 
 7   Student                 87014 non-null  object 
 8   EdLevel                 86390 non-null  object 
 9   UndergradMajor          75614 non-null  object 
 10  EduOther                84260 non-null  object 
 11  OrgSize                 71791 non-null  object 
 12  DevType                 81335 non-null  object 
 13  YearsCode               87938 non-null  object 
 14  Age1stCode              87634 non-null

In [42]:
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   

                  OpenSourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   

                               Employment                 Country  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   
2                      Employed full-time                Thailand   
3                      Employed full-time           United States   
4                      Employed full-time                 Ukraine   

          Student                                            EdLevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  ...  \
0                                                NaN  ...   
1                                                NaN  ...   
2                      Web development or web design  ...   
3  Computer science, computer engineering, or sof...  ...   
4  Computer science, computer engineering, or sof...  ...   

                             WelcomeChange  \
0  Just as welcome now as I felt last year   
1  Just as welcome now as I felt last year   
2  Just as welcome now as I felt last year   
3  Just as welcome now as I felt last year   
4  Just as welcome now as I felt last year   

                                        SONewContent   Age Gender Trans  \
0  Tech articles written by other developers;Indu...  14.0    Man    No   
1  Tech articles written by other developers;Indu...  19.0    Man    No   
2  Tech meetups or events in your area;Courses on...  28.0    Man    No   
3  Tech articles written by other developers;Indu...  22.0    Man    No   
4  Tech meetups or events in your area;Courses on...  30.0    Man    No   

                 Sexuality                                 Ethnicity  \
0  Straight / Heterosexual                                       NaN   
1  Straight / Heterosexual                                       NaN   
2  Straight / Heterosexual                                       NaN   
3  Straight / Heterosexual              White or of European descent   
4  Straight / Heterosexual  White or of European descent;Multiracial   

  Dependents           SurveyLength                  SurveyEase  
0         No  Appropriate in length  Neither easy nor difficult  
1         No  Appropriate in length  Neither easy nor difficult  
2        Yes  Appropriate in length  Neither easy nor difficult  
3         No  Appropriate in length                        Easy  
4         No  Appropriate in length                        Easy  

[5 rows x 85 columns]

In [43]:
df.tail()

Respondent MainBranch Hobbyist  \
88878       88377        NaN      Yes   
88879       88601        NaN       No   
88880       88802        NaN       No   
88881       88816        NaN       No   
88882       88863        NaN      Yes   

                                             OpenSourcer  \
88878  Less than once a month but more than once per ...   
88879                                              Never   
88880                                              Never   
88881                                              Never   
88882                            Less than once per year   

                                              OpenSource  \
88878  The quality of OSS and closed source software ...   
88879  The quality of OSS and closed source software ...   
88880                                                NaN   
88881  OSS is, on average, of HIGHER quality than pro...   
88882  OSS is, on average, of HIGHER quality than pro...   

                                              Employment Country  \
88878             Not employed, and not looking for work  Canada   
88879                                                NaN     NaN   
88880                                 Employed full-time     NaN   
88881  Independent contractor, freelancer, or self-em...     NaN   
88882             Not employed, and not looking for work   Spain   

              Student                             EdLevel  \
88878              No           Primary/elementary school   
88879             NaN                                 NaN   
88880             NaN                                 NaN   
88881             NaN                                 NaN   
88882  Yes, full-time  Professional degree (JD, MD, etc.)   

                                          UndergradMajor  ...  \
88878                                                NaN  ...   
88879                                                NaN  ...   
88880                                                NaN  ...   
88881                                                NaN  ...   
88882  Computer science, computer engineering, or sof...  ...   

                                  WelcomeChange  \
88878                                       NaN   
88879                                       NaN   
88880                                       NaN   
88881                                       NaN   
88882  Somewhat less welcome now than last year   

                                            SONewContent   Age Gender Trans  \
88878  Tech articles written by other developers;Tech...   NaN    Man    No   
88879                                                NaN   NaN    NaN   NaN   
88880                                                NaN   NaN    NaN   NaN   
88881                                                NaN   NaN    NaN   NaN   
88882  Tech articles written by other developers;Indu...  18.0    Man    No   

                     Sexuality  \
88878                      NaN   
88879                      NaN   
88880                      NaN   
88881                      NaN   
88882  Straight / Heterosexual   

                                               Ethnicity Dependents  \
88878                                                NaN         No   
88879                                                NaN        NaN   
88880                                                NaN        NaN   
88881                                                NaN        NaN   
88882  Hispanic or Latino/Latina;White or of European...         No   

                SurveyLength SurveyEase  
88878  Appropriate in length       Easy  
88879                    NaN        NaN  
88880                    NaN        NaN  
88881                    NaN        NaN  
88882  Appropriate in length       Easy  

[5 rows x 85 columns]

In [20]:
pd.set_option('display.max_rows',87)
print(df)

       Respondent                                         MainBranch Hobbyist  \
0               1             I am a student who is learning to code      Yes   
1               2             I am a student who is learning to code       No   
2               3  I am not primarily a developer, but I write co...      Yes   
3               4                     I am a developer by profession       No   
4               5                     I am a developer by profession      Yes   
...           ...                                                ...      ...   
88878       88377                                                NaN      Yes   
88879       88601                                                NaN       No   
88880       88802                                                NaN       No   
88881       88816                                                NaN       No   
88882       88863                                                NaN      Yes   

                           

In [22]:
!pip install scipy
  # For mode calculation


   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.6 MB ? eta -:--:--
    --------------------------------------- 0.8/38.6 MB 2.4 MB/s eta 0:00:16
   - -------------------------------------- 1.6/38.6 MB 2.7 MB/s eta 0:00:14
   -- ------------------------------------- 2.1/38.6 MB 2.7 MB/s eta 0:00:14
   -- ------------------------------------- 2.9/38.6 MB 2.8 MB/s eta 0:00:13
   --- ------------------------------------ 3.4/38.6 MB 2.8 MB/s eta 0:00:13
   ---- ----------------------------------- 3.9/38.6 MB 2.9 MB/s eta 0:00:13
   ----- ---------------------------------- 5.2/38.6 MB 3.2 MB/s eta 0:00:11
   ------ --------------------------------- 6.6/38.6 MB 3.5 MB/s eta 0:00:10
   -------- ------------------------------- 7.9/38.6 MB 3.8 MB/s eta 0:00:09
   --------- ------------------------------ 9.2/38.6 MB 4.1 MB/s eta 0:00:08
   ----------- ---------------------------- 10.7/38.6 MB 4.3 MB/s eta 0:00:07
   ---------

In [23]:
import numpy as np
from scipy import stats 

In [24]:
array_3d = np.random.randint(1, 100, (3, 4, 5))  # Random integers from 1 to 99
print("3D Array:\n", array_3d)

3D Array:
 [[[57 89 16 96 62]
  [72 42 85 88 20]
  [16 58 59 34 47]
  [28 21 45 15 70]]

 [[58 16 28 27 42]
  [96 37  3 77 82]
  [40 35 96 68 97]
  [41 79 31 33 12]]

 [[45  5 42 45 69]
  [68 72 20 87 36]
  [95 39 48 67 94]
  [79 16 83 93 54]]]


In [25]:
#Calculating Max
max_value = np.max(array_3d)
print("Maximum value:", max_value)


Maximum value: 97


In [26]:
#Calculating Min
min_value = np.min(array_3d)
print("Minimum value:", min_value)


Minimum value: 3


In [27]:
#Mean 
mean_value = np.mean(array_3d)
print("Mean value:", mean_value)


Mean value: 52.916666666666664


In [29]:
#Mode
mode_value = stats.mode(array_3d, axis=None)
print("Mode value:", mode_value.mode.item(), " | Count:", mode_value.count.item())



Mode value: 16  | Count: 4


In [30]:
#Median
median_value = np.median(array_3d)
print("Median value:", median_value)


Median value: 47.5
